### PR TITLE
fix(autoware_vehicle_cmd_gate): remove unused variable

### PR DESCRIPTION
**Pull request by veqcc**
## Description

Removed unused `is_filtered_marker_published_` variable.

This solves the following clang-tidy error
```
clang-tidy-14 --use-color -p=build/ /home/veqcc/work/autoware/src/universe/autoware.universe/control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
/home/veqcc/work/autoware/src/universe/autoware.universe/control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.hpp:140:8: error: private field 'is_filtered_marker_published_' is not used [clang-diagnostic-unused-private-field]
  bool is_filtered_marker_published_ = false;
       ^
1 error generated.
Error while processing /home/veqcc/work/autoware/src/universe/autoware.universe/control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp.
Found compiler error(s).
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by veqcc** [comment]
@TakaHoribe @tkimura4 
Hi, this is really a simple PR, so please approve it. Thank you!

**Comment by veqcc** [comment]
@TakaHoribe @tkimura4 
Hi

**Review by TakaHoribe — APPROVED** [review]
Note: This variable was introduced in https://github.com/autowarefoundation/autoware.universe/pull/5426/files, but never used even in the PR. I believe this was wrongly declared.

Thank you, LGTM.
